import {
    breakpoints,
    sides,
    useHeadingTagOptions,
    useAuthorOptions,
    useAuthors,
    useBgAttachmentOptions,
    useBgColorOptions,
    useBgPositionOptions,
    useBgSizeOptions,
    useBorderColorOptions,
    useBorderRadiusOptions,
    useBorderSizeOptions,
    useBorderStyleOptions,
    useButtonColorOptions,
    useButtonSizeOptions,
    useCategories,
    useCategoryOptions,
    useColorOptions,
    useColors,
    useColspanOptions,
    useContainerTypeOptions,
    useFontSizeOptions,
    useFontStyleOptions,
    useFontWeightOptions,
    useGapOptions,
    useGridColsOptions,
    useMarginOptions,
    usePaddingOptions,
    useShadowColorOptions,
    useShadowSizeOptions,
    useSortOptions,
    useTagOptions,
    useTags,
    useTextAlignOptions,
    useTextColorOptions,
    useTextTransformOptions,
    useThemeOptions,
    useUserOptions,
    useUsers,
    usePositionOptions,
    useDisplayOptions,
    useFlexDirectionOptions,
    useAlignItemsOptions,
    useJustifyContentOptions,
    breakpointTabs,
    useInsetOptions,
    useZindexOptions,
    sideOptions,
    useSizeOptions,
    useLinkTypeOptions,
} from "@/composables/options";
import { useLayoutOptions } from "./options/layout";
export const useOptions = () => {
    return {
        breakpoints,
        breakpointTabs,
        sides,
        sideOptions,
        headingTagOptions: useHeadingTagOptions(),
        textColorOptions: useTextColorOptions(),
        textAlignOptions: useTextAlignOptions(),
        fontSizeOptions: useFontSizeOptions(),
        fontWeightOptions: useFontWeightOptions(),
        fontStyleOptions: useFontStyleOptions(),
        textTransformOptions: useTextTransformOptions(),
        bgColorOptions: useBgColorOptions(),
        bgSizeOptions: useBgSizeOptions(),
        bgPositionOptions: useBgPositionOptions(),
        bgAttachmentOptions: useBgAttachmentOptions(),
        buttonSizeOptions: useButtonSizeOptions(),
        categoryOptions: useCategoryOptions(),
        tagOptions: useTagOptions(),
        authorOptions: useAuthorOptions(),
        userOptions: useUserOptions(),
        sortOptions: useSortOptions(),
        containerTypeOptions: useContainerTypeOptions(),
        gridColsOptions: useGridColsOptions(),
        gapOptions: useGapOptions(),
        colspanOptions: useColspanOptions(),
        marginOptions: useMarginOptions(),
        paddingOptions: usePaddingOptions(),
        borderColorOptions: useBorderColorOptions(),
        borderSizeOptions: useBorderSizeOptions(),
        borderStyleOptions: useBorderStyleOptions(),
        borderRadiusOptions: useBorderRadiusOptions(),
        shadowSizeOptions: useShadowSizeOptions(),
        shadowColorOptions: useShadowColorOptions(),
        buttonColorOptions: useButtonColorOptions(),
        themeOptions: useThemeOptions(),
        positionOptions: usePositionOptions(),
        displayOptions: useDisplayOptions(),
        flexDirectionOptions: useFlexDirectionOptions(),
        alignItemsOptions: useAlignItemsOptions(),
        justifyContentOptions: useJustifyContentOptions(),
        insetOptions: useInsetOptions(),
        zIndexOptions: useZindexOptions(),
        sizeOptions: useSizeOptions(),
        linkTypeOptions: useLinkTypeOptions(),
        layoutOptions: useLayoutOptions(),
    };
};
