import { Block } from "@/types";

export const defaultBlocks = (): Block[] => {
    return [
        {
            type: "container",
            id: "block-s15phia",
            attributes: {
                type: "container-fluid",
                textColor: "",
                fontSize: "",
                fontWeight: "",
                fontStyle: "",
                textTransform: "",
                textAlign: "",
                bgColor: "bg-white",
                bgImage: "",
                bgSize: "",
                bgPosition: "",
                bgAttachment: "",
                margin: {
                    sm: {
                        top: "mt-4",
                        start: "ms-4",
                        end: "me-4",
                        bottom: "mb-4",
                    },
                    md: {
                        top: "",
                        start: "",
                        end: "",
                        bottom: "",
                    },
                    lg: {
                        top: "",
                        start: "",
                        end: "",
                        bottom: "",
                    },
                    xl: {
                        top: "",
                        start: "",
                        end: "",
                        bottom: "",
                    },
                },
                padding: {
                    sm: {
                        top: "pt-4",
                        start: "ps-4",
                        end: "pe-4",
                        bottom: "pb-4",
                    },
                    md: {
                        top: "",
                        start: "",
                        end: "",
                        bottom: "",
                    },
                    lg: {
                        top: "",
                        start: "",
                        end: "",
                        bottom: "",
                    },
                    xl: {
                        top: "",
                        start: "",
                        end: "",
                        bottom: "",
                    },
                },
                borderSize: "border-1",
                borderColor: "border-red",
                borderStyle: "border-dashed",
                borderRadius: "",
                shadowSize: "",
                shadowColor: "",
                position: {
                    sm: null,
                    md: null,
                    lg: null,
                    xl: null,
                },
                display: {
                    sm: null,
                    md: null,
                    lg: null,
                    xl: null,
                },
                flexDirection: {
                    sm: null,
                    md: null,
                    lg: null,
                    xl: null,
                },
                alignItems: {
                    sm: null,
                    md: null,
                    lg: null,
                    xl: null,
                },
                justifyContent: {
                    sm: null,
                    md: null,
                    lg: null,
                    xl: null,
                },
                inset: {
                    sm: {
                        top: "",
                        start: "",
                        end: "",
                        bottom: "",
                    },
                    md: {
                        top: "",
                        start: "",
                        end: "",
                        bottom: "",
                    },
                    lg: {
                        top: "",
                        start: "",
                        end: "",
                        bottom: "",
                    },
                    xl: {
                        top: "",
                        start: "",
                        end: "",
                        bottom: "",
                    },
                },
                zIndex: "",
                htmlAnchor: "parent-container",
                className: "",
                style: "",
            },
            children: [
                {
                    type: "container",
                    id: "block-d9t6at1",
                    attributes: {
                        type: "container",
                        textColor: "",
                        fontSize: "",
                        fontWeight: "",
                        fontStyle: "",
                        textTransform: "",
                        textAlign: "",
                        bgColor: "",
                        bgImage: "",
                        bgSize: "",
                        bgPosition: "",
                        bgAttachment: "",
                        margin: {
                            sm: {
                                top: "mt-7",
                                start: "ms-7",
                                end: "me-7",
                                bottom: "mb-7",
                            },
                            md: {
                                top: "",
                                start: "",
                                end: "",
                                bottom: "",
                            },
                            lg: {
                                top: "",
                                start: "",
                                end: "",
                                bottom: "",
                            },
                            xl: {
                                top: "",
                                start: "",
                                end: "",
                                bottom: "",
                            },
                        },
                        padding: {
                            sm: {
                                top: "pt-7",
                                start: "ps-7",
                                end: "pe-7",
                                bottom: "pb-7",
                            },
                            md: {
                                top: "",
                                start: "",
                                end: "",
                                bottom: "",
                            },
                            lg: {
                                top: "",
                                start: "",
                                end: "",
                                bottom: "",
                            },
                            xl: {
                                top: "",
                                start: "",
                                end: "",
                                bottom: "",
                            },
                        },
                        borderSize: "border-1",
                        borderColor: "border-green",
                        borderStyle: "border-dashed",
                        borderRadius: "",
                        shadowSize: "",
                        shadowColor: "",
                        position: {
                            sm: null,
                            md: null,
                            lg: null,
                            xl: null,
                        },
                        display: {
                            sm: null,
                            md: null,
                            lg: null,
                            xl: null,
                        },
                        flexDirection: {
                            sm: null,
                            md: null,
                            lg: null,
                            xl: null,
                        },
                        alignItems: {
                            sm: null,
                            md: null,
                            lg: null,
                            xl: null,
                        },
                        justifyContent: {
                            sm: null,
                            md: null,
                            lg: null,
                            xl: null,
                        },
                        inset: {
                            sm: {
                                top: "",
                                start: "",
                                end: "",
                                bottom: "",
                            },
                            md: {
                                top: "",
                                start: "",
                                end: "",
                                bottom: "",
                            },
                            lg: {
                                top: "",
                                start: "",
                                end: "",
                                bottom: "",
                            },
                            xl: {
                                top: "",
                                start: "",
                                end: "",
                                bottom: "",
                            },
                        },
                        zIndex: "",
                        htmlAnchor: "child-container",
                        className: "",
                        style: "",
                    },
                    children: [],
                },
            ],
        },
    ];
};
