export const useInsetOptions = () => {
    return {
        sm: {
            top: [
                { label: "none", value: "" },
                { label: "auto", value: "top-auto" },
                { label: "0", value: "top-0" },
                { label: "1", value: "top-1" },
                { label: "2", value: "top-2" },
                { label: "3", value: "top-3" },
                { label: "4", value: "top-4" },
                { label: "5", value: "top-5" },
                { label: "6", value: "top-6" },
                { label: "7", value: "top-7" },
                { label: "8", value: "top-8" },
                { label: "9", value: "top-9" },
                { label: "10", value: "top-10" },
                { label: "full", value: "top-full" },
                { label: "-1", value: "-top-1" },
                { label: "-2", value: "-top-2" },
                { label: "-3", value: "-top-3" },
                { label: "-4", value: "-top-4" },
                { label: "-5", value: "-top-5" },
                { label: "-6", value: "-top-6" },
                { label: "-7", value: "-top-7" },
                { label: "-8", value: "-top-8" },
                { label: "-9", value: "-top-9" },
                { label: "-10", value: "-top-10" },
                { label: "-full", value: "-top-full" },
            ],
            start: [
                { label: "none", value: "" },
                { label: "auto", value: "start-auto" },
                { label: "0", value: "start-0" },
                { label: "1", value: "start-1" },
                { label: "2", value: "start-2" },
                { label: "3", value: "start-3" },
                { label: "4", value: "start-4" },
                { label: "5", value: "start-5" },
                { label: "6", value: "start-6" },
                { label: "7", value: "start-7" },
                { label: "8", value: "start-8" },
                { label: "9", value: "start-9" },
                { label: "10", value: "start-10" },
                { label: "full", value: "start-full" },
                { label: "-1", value: "-start-1" },
                { label: "-2", value: "-start-2" },
                { label: "-3", value: "-start-3" },
                { label: "-4", value: "-start-4" },
                { label: "-5", value: "-start-5" },
                { label: "-6", value: "-start-6" },
                { label: "-7", value: "-start-7" },
                { label: "-8", value: "-start-8" },
                { label: "-9", value: "-start-9" },
                { label: "-10", value: "-start-10" },
                { label: "-full", value: "-start-full" },
            ],
            end: [
                { label: "none", value: "" },
                { label: "auto", value: "end-auto" },
                { label: "0", value: "end-0" },
                { label: "1", value: "end-1" },
                { label: "2", value: "end-2" },
                { label: "3", value: "end-3" },
                { label: "4", value: "end-4" },
                { label: "5", value: "end-5" },
                { label: "6", value: "end-6" },
                { label: "7", value: "end-7" },
                { label: "8", value: "end-8" },
                { label: "9", value: "end-9" },
                { label: "10", value: "end-10" },
                { label: "full", value: "end-full" },
                { label: "-1", value: "-end-1" },
                { label: "-2", value: "-end-2" },
                { label: "-3", value: "-end-3" },
                { label: "-4", value: "-end-4" },
                { label: "-5", value: "-end-5" },
                { label: "-6", value: "-end-6" },
                { label: "-7", value: "-end-7" },
                { label: "-8", value: "-end-8" },
                { label: "-9", value: "-end-9" },
                { label: "-10", value: "-end-10" },
                { label: "-full", value: "-end-full" },
            ],
            bottom: [
                { label: "none", value: "" },
                { label: "auto", value: "bottom-auto" },
                { label: "0", value: "bottom-0" },
                { label: "1", value: "bottom-1" },
                { label: "2", value: "bottom-2" },
                { label: "3", value: "bottom-3" },
                { label: "4", value: "bottom-4" },
                { label: "5", value: "bottom-5" },
                { label: "6", value: "bottom-6" },
                { label: "7", value: "bottom-7" },
                { label: "8", value: "bottom-8" },
                { label: "9", value: "bottom-9" },
                { label: "10", value: "bottom-10" },
                { label: "full", value: "bottom-full" },
                { label: "-1", value: "-bottom-1" },
                { label: "-2", value: "-bottom-2" },
                { label: "-3", value: "-bottom-3" },
                { label: "-4", value: "-bottom-4" },
                { label: "-5", value: "-bottom-5" },
                { label: "-6", value: "-bottom-6" },
                { label: "-7", value: "-bottom-7" },
                { label: "-8", value: "-bottom-8" },
                { label: "-9", value: "-bottom-9" },
                { label: "-10", value: "-bottom-10" },
                { label: "-full", value: "-bottom-full" },
            ],
        },
        md: {
            top: [
                { label: "none", value: "" },
                { label: "auto", value: "md:top-auto" },
                { label: "0", value: "md:top-0" },
                { label: "1", value: "md:top-1" },
                { label: "2", value: "md:top-2" },
                { label: "3", value: "md:top-3" },
                { label: "4", value: "md:top-4" },
                { label: "5", value: "md:top-5" },
                { label: "6", value: "md:top-6" },
                { label: "7", value: "md:top-7" },
                { label: "8", value: "md:top-8" },
                { label: "9", value: "md:top-9" },
                { label: "10", value: "md:top-10" },
                { label: "full", value: "md:top-full" },
                { label: "-1", value: "md:-top-1" },
                { label: "-2", value: "md:-top-2" },
                { label: "-3", value: "md:-top-3" },
                { label: "-4", value: "md:-top-4" },
                { label: "-5", value: "md:-top-5" },
                { label: "-6", value: "md:-top-6" },
                { label: "-7", value: "md:-top-7" },
                { label: "-8", value: "md:-top-8" },
                { label: "-9", value: "md:-top-9" },
                { label: "-10", value: "md:-top-10" },
                { label: "-full", value: "md:-top-full" },
            ],
            start: [
                { label: "none", value: "" },
                { label: "auto", value: "md:start-auto" },
                { label: "0", value: "md:start-0" },
                { label: "1", value: "md:start-1" },
                { label: "2", value: "md:start-2" },
                { label: "3", value: "md:start-3" },
                { label: "4", value: "md:start-4" },
                { label: "5", value: "md:start-5" },
                { label: "6", value: "md:start-6" },
                { label: "7", value: "md:start-7" },
                { label: "8", value: "md:start-8" },
                { label: "9", value: "md:start-9" },
                { label: "10", value: "md:start-10" },
                { label: "full", value: "md:start-full" },
                { label: "-1", value: "md:-start-1" },
                { label: "-2", value: "md:-start-2" },
                { label: "-3", value: "md:-start-3" },
                { label: "-4", value: "md:-start-4" },
                { label: "-5", value: "md:-start-5" },
                { label: "-6", value: "md:-start-6" },
                { label: "-7", value: "md:-start-7" },
                { label: "-8", value: "md:-start-8" },
                { label: "-9", value: "md:-start-9" },
                { label: "-10", value: "md:-start-10" },
                { label: "-full", value: "md:-start-full" },
            ],
            end: [
                { label: "none", value: "" },
                { label: "auto", value: "md:end-auto" },
                { label: "0", value: "md:end-0" },
                { label: "1", value: "md:end-1" },
                { label: "2", value: "md:end-2" },
                { label: "3", value: "md:end-3" },
                { label: "4", value: "md:end-4" },
                { label: "5", value: "md:end-5" },
                { label: "6", value: "md:end-6" },
                { label: "7", value: "md:end-7" },
                { label: "8", value: "md:end-8" },
                { label: "9", value: "md:end-9" },
                { label: "10", value: "md:end-10" },
                { label: "full", value: "md:end-full" },
                { label: "-1", value: "md:-end-1" },
                { label: "-2", value: "md:-end-2" },
                { label: "-3", value: "md:-end-3" },
                { label: "-4", value: "md:-end-4" },
                { label: "-5", value: "md:-end-5" },
                { label: "-6", value: "md:-end-6" },
                { label: "-7", value: "md:-end-7" },
                { label: "-8", value: "md:-end-8" },
                { label: "-9", value: "md:-end-9" },
                { label: "-10", value: "md:-end-10" },
                { label: "-full", value: "md:-end-full" },
            ],
            bottom: [
                { label: "none", value: "" },
                { label: "auto", value: "md:bottom-auto" },
                { label: "0", value: "md:bottom-0" },
                { label: "1", value: "md:bottom-1" },
                { label: "2", value: "md:bottom-2" },
                { label: "3", value: "md:bottom-3" },
                { label: "4", value: "md:bottom-4" },
                { label: "5", value: "md:bottom-5" },
                { label: "6", value: "md:bottom-6" },
                { label: "7", value: "md:bottom-7" },
                { label: "8", value: "md:bottom-8" },
                { label: "9", value: "md:bottom-9" },
                { label: "10", value: "md:bottom-10" },
                { label: "full", value: "md:bottom-full" },
                { label: "-1", value: "md:-bottom-1" },
                { label: "-2", value: "md:-bottom-2" },
                { label: "-3", value: "md:-bottom-3" },
                { label: "-4", value: "md:-bottom-4" },
                { label: "-5", value: "md:-bottom-5" },
                { label: "-6", value: "md:-bottom-6" },
                { label: "-7", value: "md:-bottom-7" },
                { label: "-8", value: "md:-bottom-8" },
                { label: "-9", value: "md:-bottom-9" },
                { label: "-10", value: "md:-bottom-10" },
                { label: "-full", value: "md:-bottom-full" },
            ],
        },
        lg: {
            top: [
                { label: "none", value: "" },
                { label: "auto", value: "lg:top-auto" },
                { label: "0", value: "lg:top-0" },
                { label: "1", value: "lg:top-1" },
                { label: "2", value: "lg:top-2" },
                { label: "3", value: "lg:top-3" },
                { label: "4", value: "lg:top-4" },
                { label: "5", value: "lg:top-5" },
                { label: "6", value: "lg:top-6" },
                { label: "7", value: "lg:top-7" },
                { label: "8", value: "lg:top-8" },
                { label: "9", value: "lg:top-9" },
                { label: "10", value: "lg:top-10" },
                { label: "full", value: "lg:top-full" },
                { label: "-1", value: "lg:-top-1" },
                { label: "-2", value: "lg:-top-2" },
                { label: "-3", value: "lg:-top-3" },
                { label: "-4", value: "lg:-top-4" },
                { label: "-5", value: "lg:-top-5" },
                { label: "-6", value: "lg:-top-6" },
                { label: "-7", value: "lg:-top-7" },
                { label: "-8", value: "lg:-top-8" },
                { label: "-9", value: "lg:-top-9" },
                { label: "-10", value: "lg:-top-10" },
                { label: "-full", value: "lg:-top-full" },
            ],
            start: [
                { label: "none", value: "" },
                { label: "auto", value: "lg:start-auto" },
                { label: "0", value: "lg:start-0" },
                { label: "1", value: "lg:start-1" },
                { label: "2", value: "lg:start-2" },
                { label: "3", value: "lg:start-3" },
                { label: "4", value: "lg:start-4" },
                { label: "5", value: "lg:start-5" },
                { label: "6", value: "lg:start-6" },
                { label: "7", value: "lg:start-7" },
                { label: "8", value: "lg:start-8" },
                { label: "9", value: "lg:start-9" },
                { label: "10", value: "lg:start-10" },
                { label: "full", value: "lg:start-full" },
                { label: "-1", value: "lg:-start-1" },
                { label: "-2", value: "lg:-start-2" },
                { label: "-3", value: "lg:-start-3" },
                { label: "-4", value: "lg:-start-4" },
                { label: "-5", value: "lg:-start-5" },
                { label: "-6", value: "lg:-start-6" },
                { label: "-7", value: "lg:-start-7" },
                { label: "-8", value: "lg:-start-8" },
                { label: "-9", value: "lg:-start-9" },
                { label: "-10", value: "lg:-start-10" },
                { label: "-full", value: "lg:-start-full" },
            ],
            end: [
                { label: "none", value: "" },
                { label: "auto", value: "lg:end-auto" },
                { label: "0", value: "lg:end-0" },
                { label: "1", value: "lg:end-1" },
                { label: "2", value: "lg:end-2" },
                { label: "3", value: "lg:end-3" },
                { label: "4", value: "lg:end-4" },
                { label: "5", value: "lg:end-5" },
                { label: "6", value: "lg:end-6" },
                { label: "7", value: "lg:end-7" },
                { label: "8", value: "lg:end-8" },
                { label: "9", value: "lg:end-9" },
                { label: "10", value: "lg:end-10" },
                { label: "full", value: "lg:end-full" },
                { label: "-1", value: "lg:-end-1" },
                { label: "-2", value: "lg:-end-2" },
                { label: "-3", value: "lg:-end-3" },
                { label: "-4", value: "lg:-end-4" },
                { label: "-5", value: "lg:-end-5" },
                { label: "-6", value: "lg:-end-6" },
                { label: "-7", value: "lg:-end-7" },
                { label: "-8", value: "lg:-end-8" },
                { label: "-9", value: "lg:-end-9" },
                { label: "-10", value: "lg:-end-10" },
                { label: "-full", value: "lg:-end-full" },
            ],
            bottom: [
                { label: "none", value: "" },
                { label: "auto", value: "lg:bottom-auto" },
                { label: "0", value: "lg:bottom-0" },
                { label: "1", value: "lg:bottom-1" },
                { label: "2", value: "lg:bottom-2" },
                { label: "3", value: "lg:bottom-3" },
                { label: "4", value: "lg:bottom-4" },
                { label: "5", value: "lg:bottom-5" },
                { label: "6", value: "lg:bottom-6" },
                { label: "7", value: "lg:bottom-7" },
                { label: "8", value: "lg:bottom-8" },
                { label: "9", value: "lg:bottom-9" },
                { label: "10", value: "lg:bottom-10" },
                { label: "full", value: "lg:bottom-full" },
                { label: "-1", value: "lg:-bottom-1" },
                { label: "-2", value: "lg:-bottom-2" },
                { label: "-3", value: "lg:-bottom-3" },
                { label: "-4", value: "lg:-bottom-4" },
                { label: "-5", value: "lg:-bottom-5" },
                { label: "-6", value: "lg:-bottom-6" },
                { label: "-7", value: "lg:-bottom-7" },
                { label: "-8", value: "lg:-bottom-8" },
                { label: "-9", value: "lg:-bottom-9" },
                { label: "-10", value: "lg:-bottom-10" },
                { label: "-full", value: "lg:-bottom-full" },
            ],
        },
        xl: {
            top: [
                { label: "none", value: "" },
                { label: "auto", value: "xl:top-auto" },
                { label: "0", value: "xl:top-0" },
                { label: "1", value: "xl:top-1" },
                { label: "2", value: "xl:top-2" },
                { label: "3", value: "xl:top-3" },
                { label: "4", value: "xl:top-4" },
                { label: "5", value: "xl:top-5" },
                { label: "6", value: "xl:top-6" },
                { label: "7", value: "xl:top-7" },
                { label: "8", value: "xl:top-8" },
                { label: "9", value: "xl:top-9" },
                { label: "10", value: "xl:top-10" },
                { label: "full", value: "xl:top-full" },
                { label: "-1", value: "xl:-top-1" },
                { label: "-2", value: "xl:-top-2" },
                { label: "-3", value: "xl:-top-3" },
                { label: "-4", value: "xl:-top-4" },
                { label: "-5", value: "xl:-top-5" },
                { label: "-6", value: "xl:-top-6" },
                { label: "-7", value: "xl:-top-7" },
                { label: "-8", value: "xl:-top-8" },
                { label: "-9", value: "xl:-top-9" },
                { label: "-10", value: "xl:-top-10" },
                { label: "-full", value: "xl:-top-full" },
            ],
            start: [
                { label: "none", value: "" },
                { label: "auto", value: "xl:start-auto" },
                { label: "0", value: "xl:start-0" },
                { label: "1", value: "xl:start-1" },
                { label: "2", value: "xl:start-2" },
                { label: "3", value: "xl:start-3" },
                { label: "4", value: "xl:start-4" },
                { label: "5", value: "xl:start-5" },
                { label: "6", value: "xl:start-6" },
                { label: "7", value: "xl:start-7" },
                { label: "8", value: "xl:start-8" },
                { label: "9", value: "xl:start-9" },
                { label: "10", value: "xl:start-10" },
                { label: "full", value: "xl:start-full" },
                { label: "-1", value: "xl:-start-1" },
                { label: "-2", value: "xl:-start-2" },
                { label: "-3", value: "xl:-start-3" },
                { label: "-4", value: "xl:-start-4" },
                { label: "-5", value: "xl:-start-5" },
                { label: "-6", value: "xl:-start-6" },
                { label: "-7", value: "xl:-start-7" },
                { label: "-8", value: "xl:-start-8" },
                { label: "-9", value: "xl:-start-9" },
                { label: "-10", value: "xl:-start-10" },
                { label: "-full", value: "xl:-start-full" },
            ],
            end: [
                { label: "none", value: "" },
                { label: "auto", value: "xl:end-auto" },
                { label: "0", value: "xl:end-0" },
                { label: "1", value: "xl:end-1" },
                { label: "2", value: "xl:end-2" },
                { label: "3", value: "xl:end-3" },
                { label: "4", value: "xl:end-4" },
                { label: "5", value: "xl:end-5" },
                { label: "6", value: "xl:end-6" },
                { label: "7", value: "xl:end-7" },
                { label: "8", value: "xl:end-8" },
                { label: "9", value: "xl:end-9" },
                { label: "10", value: "xl:end-10" },
                { label: "full", value: "xl:end-full" },
                { label: "-1", value: "xl:-end-1" },
                { label: "-2", value: "xl:-end-2" },
                { label: "-3", value: "xl:-end-3" },
                { label: "-4", value: "xl:-end-4" },
                { label: "-5", value: "xl:-end-5" },
                { label: "-6", value: "xl:-end-6" },
                { label: "-7", value: "xl:-end-7" },
                { label: "-8", value: "xl:-end-8" },
                { label: "-9", value: "xl:-end-9" },
                { label: "-10", value: "xl:-end-10" },
                { label: "-full", value: "xl:-end-full" },
            ],
            bottom: [
                { label: "none", value: "" },
                { label: "auto", value: "xl:bottom-auto" },
                { label: "0", value: "xl:bottom-0" },
                { label: "1", value: "xl:bottom-1" },
                { label: "2", value: "xl:bottom-2" },
                { label: "3", value: "xl:bottom-3" },
                { label: "4", value: "xl:bottom-4" },
                { label: "5", value: "xl:bottom-5" },
                { label: "6", value: "xl:bottom-6" },
                { label: "7", value: "xl:bottom-7" },
                { label: "8", value: "xl:bottom-8" },
                { label: "9", value: "xl:bottom-9" },
                { label: "10", value: "xl:bottom-10" },
                { label: "full", value: "xl:bottom-full" },
                { label: "-1", value: "xl:-bottom-1" },
                { label: "-2", value: "xl:-bottom-2" },
                { label: "-3", value: "xl:-bottom-3" },
                { label: "-4", value: "xl:-bottom-4" },
                { label: "-5", value: "xl:-bottom-5" },
                { label: "-6", value: "xl:-bottom-6" },
                { label: "-7", value: "xl:-bottom-7" },
                { label: "-8", value: "xl:-bottom-8" },
                { label: "-9", value: "xl:-bottom-9" },
                { label: "-10", value: "xl:-bottom-10" },
                { label: "-full", value: "xl:-bottom-full" },
            ],
        },
    };
};
