export const useMarginOptions = () => {
    return {
        sm: {
            top: [
                { label: "none", value: "" },
                { label: "auto", value: "mt-auto" },
                { label: "0", value: "mt-0" },
                { label: "1", value: "mt-1" },
                { label: "2", value: "mt-2" },
                { label: "3", value: "mt-3" },
                { label: "4", value: "mt-4" },
                { label: "5", value: "mt-5" },
                { label: "6", value: "mt-6" },
                { label: "7", value: "mt-7" },
                { label: "8", value: "mt-8" },
                { label: "9", value: "mt-9" },
                { label: "10", value: "mt-10" },
            ],
            start: [
                { label: "none", value: "" },
                { label: "auto", value: "ms-auto" },
                { label: "0", value: "ms-0" },
                { label: "1", value: "ms-1" },
                { label: "2", value: "ms-2" },
                { label: "3", value: "ms-3" },
                { label: "4", value: "ms-4" },
                { label: "5", value: "ms-5" },
                { label: "6", value: "ms-6" },
                { label: "7", value: "ms-7" },
                { label: "8", value: "ms-8" },
                { label: "9", value: "ms-9" },
                { label: "10", value: "ms-10" },
            ],
            end: [
                { label: "none", value: "" },
                { label: "auto", value: "me-auto" },
                { label: "0", value: "me-0" },
                { label: "1", value: "me-1" },
                { label: "2", value: "me-2" },
                { label: "3", value: "me-3" },
                { label: "4", value: "me-4" },
                { label: "5", value: "me-5" },
                { label: "6", value: "me-6" },
                { label: "7", value: "me-7" },
                { label: "8", value: "me-8" },
                { label: "9", value: "me-9" },
                { label: "10", value: "me-10" },
            ],
            bottom: [
                { label: "none", value: "" },
                { label: "auto", value: "mb-auto" },
                { label: "0", value: "mb-0" },
                { label: "1", value: "mb-1" },
                { label: "2", value: "mb-2" },
                { label: "3", value: "mb-3" },
                { label: "4", value: "mb-4" },
                { label: "5", value: "mb-5" },
                { label: "6", value: "mb-6" },
                { label: "7", value: "mb-7" },
                { label: "8", value: "mb-8" },
                { label: "9", value: "mb-9" },
                { label: "10", value: "mb-10" },
            ],
        },
        md: {
            top: [
                { label: "none", value: "" },
                { label: "auto", value: "md:mt-auto" },
                { label: "0", value: "md:mt-0" },
                { label: "1", value: "md:mt-1" },
                { label: "2", value: "md:mt-2" },
                { label: "3", value: "md:mt-3" },
                { label: "4", value: "md:mt-4" },
                { label: "5", value: "md:mt-5" },
                { label: "6", value: "md:mt-6" },
                { label: "7", value: "md:mt-7" },
                { label: "8", value: "md:mt-8" },
                { label: "9", value: "md:mt-9" },
                { label: "10", value: "md:mt-10" },
            ],
            start: [
                { label: "none", value: "" },
                { label: "auto", value: "md:ms-auto" },
                { label: "0", value: "md:ms-0" },
                { label: "1", value: "md:ms-1" },
                { label: "2", value: "md:ms-2" },
                { label: "3", value: "md:ms-3" },
                { label: "4", value: "md:ms-4" },
                { label: "5", value: "md:ms-5" },
                { label: "6", value: "md:ms-6" },
                { label: "7", value: "md:ms-7" },
                { label: "8", value: "md:ms-8" },
                { label: "9", value: "md:ms-9" },
                { label: "10", value: "md:ms-10" },
            ],
            end: [
                { label: "none", value: "" },
                { label: "auto", value: "md:me-auto" },
                { label: "0", value: "md:me-0" },
                { label: "1", value: "md:me-1" },
                { label: "2", value: "md:me-2" },
                { label: "3", value: "md:me-3" },
                { label: "4", value: "md:me-4" },
                { label: "5", value: "md:me-5" },
                { label: "6", value: "md:me-6" },
                { label: "7", value: "md:me-7" },
                { label: "8", value: "md:me-8" },
                { label: "9", value: "md:me-9" },
                { label: "10", value: "md:me-10" },
            ],
            bottom: [
                { label: "none", value: "" },
                { label: "auto", value: "md:mb-auto" },
                { label: "0", value: "md:mb-0" },
                { label: "1", value: "md:mb-1" },
                { label: "2", value: "md:mb-2" },
                { label: "3", value: "md:mb-3" },
                { label: "4", value: "md:mb-4" },
                { label: "5", value: "md:mb-5" },
                { label: "6", value: "md:mb-6" },
                { label: "7", value: "md:mb-7" },
                { label: "8", value: "md:mb-8" },
                { label: "9", value: "md:mb-9" },
                { label: "10", value: "md:mb-10" },
            ],
        },
        lg: {
            top: [
                { label: "none", value: "" },
                { label: "auto", value: "lg:mt-auto" },
                { label: "0", value: "lg:mt-0" },
                { label: "1", value: "lg:mt-1" },
                { label: "2", value: "lg:mt-2" },
                { label: "3", value: "lg:mt-3" },
                { label: "4", value: "lg:mt-4" },
                { label: "5", value: "lg:mt-5" },
                { label: "6", value: "lg:mt-6" },
                { label: "7", value: "lg:mt-7" },
                { label: "8", value: "lg:mt-8" },
                { label: "9", value: "lg:mt-9" },
                { label: "10", value: "lg:mt-10" },
            ],
            start: [
                { label: "none", value: "" },
                { label: "auto", value: "lg:ms-auto" },
                { label: "0", value: "lg:ms-0" },
                { label: "1", value: "lg:ms-1" },
                { label: "2", value: "lg:ms-2" },
                { label: "3", value: "lg:ms-3" },
                { label: "4", value: "lg:ms-4" },
                { label: "5", value: "lg:ms-5" },
                { label: "6", value: "lg:ms-6" },
                { label: "7", value: "lg:ms-7" },
                { label: "8", value: "lg:ms-8" },
                { label: "9", value: "lg:ms-9" },
                { label: "10", value: "lg:ms-10" },
            ],
            end: [
                { label: "none", value: "" },
                { label: "auto", value: "lg:me-auto" },
                { label: "0", value: "lg:me-0" },
                { label: "1", value: "lg:me-1" },
                { label: "2", value: "lg:me-2" },
                { label: "3", value: "lg:me-3" },
                { label: "4", value: "lg:me-4" },
                { label: "5", value: "lg:me-5" },
                { label: "6", value: "lg:me-6" },
                { label: "7", value: "lg:me-7" },
                { label: "8", value: "lg:me-8" },
                { label: "9", value: "lg:me-9" },
                { label: "10", value: "lg:me-10" },
            ],
            bottom: [
                { label: "none", value: "" },
                { label: "auto", value: "lg:mb-auto" },
                { label: "0", value: "lg:mb-0" },
                { label: "1", value: "lg:mb-1" },
                { label: "2", value: "lg:mb-2" },
                { label: "3", value: "lg:mb-3" },
                { label: "4", value: "lg:mb-4" },
                { label: "5", value: "lg:mb-5" },
                { label: "6", value: "lg:mb-6" },
                { label: "7", value: "lg:mb-7" },
                { label: "8", value: "lg:mb-8" },
                { label: "9", value: "lg:mb-9" },
                { label: "10", value: "lg:mb-10" },
            ],
        },
        xl: {
            top: [
                { label: "none", value: "" },
                { label: "auto", value: "xl:mt-auto" },
                { label: "0", value: "xl:mt-0" },
                { label: "1", value: "xl:mt-1" },
                { label: "2", value: "xl:mt-2" },
                { label: "3", value: "xl:mt-3" },
                { label: "4", value: "xl:mt-4" },
                { label: "5", value: "xl:mt-5" },
                { label: "6", value: "xl:mt-6" },
                { label: "7", value: "xl:mt-7" },
                { label: "8", value: "xl:mt-8" },
                { label: "9", value: "xl:mt-9" },
                { label: "10", value: "xl:mt-10" },
            ],
            start: [
                { label: "none", value: "" },
                { label: "auto", value: "xl:ms-auto" },
                { label: "0", value: "xl:ms-0" },
                { label: "1", value: "xl:ms-1" },
                { label: "2", value: "xl:ms-2" },
                { label: "3", value: "xl:ms-3" },
                { label: "4", value: "xl:ms-4" },
                { label: "5", value: "xl:ms-5" },
                { label: "6", value: "xl:ms-6" },
                { label: "7", value: "xl:ms-7" },
                { label: "8", value: "xl:ms-8" },
                { label: "9", value: "xl:ms-9" },
                { label: "10", value: "xl:ms-10" },
            ],
            end: [
                { label: "none", value: "" },
                { label: "auto", value: "xl:me-auto" },
                { label: "0", value: "xl:me-0" },
                { label: "1", value: "xl:me-1" },
                { label: "2", value: "xl:me-2" },
                { label: "3", value: "xl:me-3" },
                { label: "4", value: "xl:me-4" },
                { label: "5", value: "xl:me-5" },
                { label: "6", value: "xl:me-6" },
                { label: "7", value: "xl:me-7" },
                { label: "8", value: "xl:me-8" },
                { label: "9", value: "xl:me-9" },
                { label: "10", value: "xl:me-10" },
            ],
            bottom: [
                { label: "none", value: "" },
                { label: "auto", value: "xl:mb-auto" },
                { label: "0", value: "xl:mb-0" },
                { label: "1", value: "xl:mb-1" },
                { label: "2", value: "xl:mb-2" },
                { label: "3", value: "xl:mb-3" },
                { label: "4", value: "xl:mb-4" },
                { label: "5", value: "xl:mb-5" },
                { label: "6", value: "xl:mb-6" },
                { label: "7", value: "xl:mb-7" },
                { label: "8", value: "xl:mb-8" },
                { label: "9", value: "xl:mb-9" },
                { label: "10", value: "xl:mb-10" },
            ],
        },
    };
};
