export const usePaddingOptions = () => {
    return {
        sm: {
            top: [
                { label: "none", value: "" },
                { label: "auto", value: "pt-auto" },
                { label: "0", value: "pt-0" },
                { label: "1", value: "pt-1" },
                { label: "2", value: "pt-2" },
                { label: "3", value: "pt-3" },
                { label: "4", value: "pt-4" },
                { label: "5", value: "pt-5" },
                { label: "6", value: "pt-6" },
                { label: "7", value: "pt-7" },
                { label: "8", value: "pt-8" },
                { label: "9", value: "pt-9" },
                { label: "10", value: "pt-10" },
            ],
            start: [
                { label: "none", value: "" },
                { label: "auto", value: "ps-auto" },
                { label: "0", value: "ps-0" },
                { label: "1", value: "ps-1" },
                { label: "2", value: "ps-2" },
                { label: "3", value: "ps-3" },
                { label: "4", value: "ps-4" },
                { label: "5", value: "ps-5" },
                { label: "6", value: "ps-6" },
                { label: "7", value: "ps-7" },
                { label: "8", value: "ps-8" },
                { label: "9", value: "ps-9" },
                { label: "10", value: "ps-10" },
            ],
            end: [
                { label: "none", value: "" },
                { label: "auto", value: "pe-auto" },
                { label: "0", value: "pe-0" },
                { label: "1", value: "pe-1" },
                { label: "2", value: "pe-2" },
                { label: "3", value: "pe-3" },
                { label: "4", value: "pe-4" },
                { label: "5", value: "pe-5" },
                { label: "6", value: "pe-6" },
                { label: "7", value: "pe-7" },
                { label: "8", value: "pe-8" },
                { label: "9", value: "pe-9" },
                { label: "10", value: "pe-10" },
            ],
            bottom: [
                { label: "none", value: "" },
                { label: "auto", value: "pb-auto" },
                { label: "0", value: "pb-0" },
                { label: "1", value: "pb-1" },
                { label: "2", value: "pb-2" },
                { label: "3", value: "pb-3" },
                { label: "4", value: "pb-4" },
                { label: "5", value: "pb-5" },
                { label: "6", value: "pb-6" },
                { label: "7", value: "pb-7" },
                { label: "8", value: "pb-8" },
                { label: "9", value: "pb-9" },
                { label: "10", value: "pb-10" },
            ],
        },
        md: {
            top: [
                { label: "none", value: "" },
                { label: "auto", value: "md:pt-auto" },
                { label: "0", value: "md:pt-0" },
                { label: "1", value: "md:pt-1" },
                { label: "2", value: "md:pt-2" },
                { label: "3", value: "md:pt-3" },
                { label: "4", value: "md:pt-4" },
                { label: "5", value: "md:pt-5" },
                { label: "6", value: "md:pt-6" },
                { label: "7", value: "md:pt-7" },
                { label: "8", value: "md:pt-8" },
                { label: "9", value: "md:pt-9" },
                { label: "10", value: "md:pt-10" },
            ],
            start: [
                { label: "none", value: "" },
                { label: "auto", value: "md:ps-auto" },
                { label: "0", value: "md:ps-0" },
                { label: "1", value: "md:ps-1" },
                { label: "2", value: "md:ps-2" },
                { label: "3", value: "md:ps-3" },
                { label: "4", value: "md:ps-4" },
                { label: "5", value: "md:ps-5" },
                { label: "6", value: "md:ps-6" },
                { label: "7", value: "md:ps-7" },
                { label: "8", value: "md:ps-8" },
                { label: "9", value: "md:ps-9" },
                { label: "10", value: "md:ps-10" },
            ],
            end: [
                { label: "none", value: "" },
                { label: "auto", value: "md:pe-auto" },
                { label: "0", value: "md:pe-0" },
                { label: "1", value: "md:pe-1" },
                { label: "2", value: "md:pe-2" },
                { label: "3", value: "md:pe-3" },
                { label: "4", value: "md:pe-4" },
                { label: "5", value: "md:pe-5" },
                { label: "6", value: "md:pe-6" },
                { label: "7", value: "md:pe-7" },
                { label: "8", value: "md:pe-8" },
                { label: "9", value: "md:pe-9" },
                { label: "10", value: "md:pe-10" },
            ],
            bottom: [
                { label: "none", value: "" },
                { label: "auto", value: "md:pb-auto" },
                { label: "0", value: "md:pb-0" },
                { label: "1", value: "md:pb-1" },
                { label: "2", value: "md:pb-2" },
                { label: "3", value: "md:pb-3" },
                { label: "4", value: "md:pb-4" },
                { label: "5", value: "md:pb-5" },
                { label: "6", value: "md:pb-6" },
                { label: "7", value: "md:pb-7" },
                { label: "8", value: "md:pb-8" },
                { label: "9", value: "md:pb-9" },
                { label: "10", value: "md:pb-10" },
            ],
        },
        lg: {
            top: [
                { label: "none", value: "" },
                { label: "auto", value: "lg:pt-auto" },
                { label: "0", value: "lg:pt-0" },
                { label: "1", value: "lg:pt-1" },
                { label: "2", value: "lg:pt-2" },
                { label: "3", value: "lg:pt-3" },
                { label: "4", value: "lg:pt-4" },
                { label: "5", value: "lg:pt-5" },
                { label: "6", value: "lg:pt-6" },
                { label: "7", value: "lg:pt-7" },
                { label: "8", value: "lg:pt-8" },
                { label: "9", value: "lg:pt-9" },
                { label: "10", value: "lg:pt-10" },
            ],
            start: [
                { label: "none", value: "" },
                { label: "auto", value: "lg:ps-auto" },
                { label: "0", value: "lg:ps-0" },
                { label: "1", value: "lg:ps-1" },
                { label: "2", value: "lg:ps-2" },
                { label: "3", value: "lg:ps-3" },
                { label: "4", value: "lg:ps-4" },
                { label: "5", value: "lg:ps-5" },
                { label: "6", value: "lg:ps-6" },
                { label: "7", value: "lg:ps-7" },
                { label: "8", value: "lg:ps-8" },
                { label: "9", value: "lg:ps-9" },
                { label: "10", value: "lg:ps-10" },
            ],
            end: [
                { label: "none", value: "" },
                { label: "auto", value: "lg:pe-auto" },
                { label: "0", value: "lg:pe-0" },
                { label: "1", value: "lg:pe-1" },
                { label: "2", value: "lg:pe-2" },
                { label: "3", value: "lg:pe-3" },
                { label: "4", value: "lg:pe-4" },
                { label: "5", value: "lg:pe-5" },
                { label: "6", value: "lg:pe-6" },
                { label: "7", value: "lg:pe-7" },
                { label: "8", value: "lg:pe-8" },
                { label: "9", value: "lg:pe-9" },
                { label: "10", value: "lg:pe-10" },
            ],
            bottom: [
                { label: "none", value: "" },
                { label: "auto", value: "lg:pb-auto" },
                { label: "0", value: "lg:pb-0" },
                { label: "1", value: "lg:pb-1" },
                { label: "2", value: "lg:pb-2" },
                { label: "3", value: "lg:pb-3" },
                { label: "4", value: "lg:pb-4" },
                { label: "5", value: "lg:pb-5" },
                { label: "6", value: "lg:pb-6" },
                { label: "7", value: "lg:pb-7" },
                { label: "8", value: "lg:pb-8" },
                { label: "9", value: "lg:pb-9" },
                { label: "10", value: "lg:pb-10" },
            ],
        },
        xl: {
            top: [
                { label: "none", value: "" },
                { label: "auto", value: "xl:pt-auto" },
                { label: "0", value: "xl:pt-0" },
                { label: "1", value: "xl:pt-1" },
                { label: "2", value: "xl:pt-2" },
                { label: "3", value: "xl:pt-3" },
                { label: "4", value: "xl:pt-4" },
                { label: "5", value: "xl:pt-5" },
                { label: "6", value: "xl:pt-6" },
                { label: "7", value: "xl:pt-7" },
                { label: "8", value: "xl:pt-8" },
                { label: "9", value: "xl:pt-9" },
                { label: "10", value: "xl:pt-10" },
            ],
            start: [
                { label: "none", value: "" },
                { label: "auto", value: "xl:ps-auto" },
                { label: "0", value: "xl:ps-0" },
                { label: "1", value: "xl:ps-1" },
                { label: "2", value: "xl:ps-2" },
                { label: "3", value: "xl:ps-3" },
                { label: "4", value: "xl:ps-4" },
                { label: "5", value: "xl:ps-5" },
                { label: "6", value: "xl:ps-6" },
                { label: "7", value: "xl:ps-7" },
                { label: "8", value: "xl:ps-8" },
                { label: "9", value: "xl:ps-9" },
                { label: "10", value: "xl:ps-10" },
            ],
            end: [
                { label: "none", value: "" },
                { label: "auto", value: "xl:pe-auto" },
                { label: "0", value: "xl:pe-0" },
                { label: "1", value: "xl:pe-1" },
                { label: "2", value: "xl:pe-2" },
                { label: "3", value: "xl:pe-3" },
                { label: "4", value: "xl:pe-4" },
                { label: "5", value: "xl:pe-5" },
                { label: "6", value: "xl:pe-6" },
                { label: "7", value: "xl:pe-7" },
                { label: "8", value: "xl:pe-8" },
                { label: "9", value: "xl:pe-9" },
                { label: "10", value: "xl:pe-10" },
            ],
            bottom: [
                { label: "none", value: "" },
                { label: "auto", value: "xl:pb-auto" },
                { label: "0", value: "xl:pb-0" },
                { label: "1", value: "xl:pb-1" },
                { label: "2", value: "xl:pb-2" },
                { label: "3", value: "xl:pb-3" },
                { label: "4", value: "xl:pb-4" },
                { label: "5", value: "xl:pb-5" },
                { label: "6", value: "xl:pb-6" },
                { label: "7", value: "xl:pb-7" },
                { label: "8", value: "xl:pb-8" },
                { label: "9", value: "xl:pb-9" },
                { label: "10", value: "xl:pb-10" },
            ],
        },
    };
};
